dist: xenial

language: python

cache: pip

python:
  #- '3.4'
  #- '3.5'
  #- '3.6'
  #- '3.7'
  - '3.8'
  #- 'pypy3'

#matrix:
#  allow_failures:
#    - python: '3.8-dev'

services:
  - docker

install:
  - pip install tox-travis

script:
  - tox -e lint

after_success:
  - pip install codecov
  - codecov -v
